### PR TITLE
Add support for custom UA string for new clients.

### PR DESCRIPTION
**Pull request by fiveisprime**
Updated the login to accept a service name to override the UA string
when instantiating clients.

Sorry for the additional diff noise, my editor trimmed out the trailing
whitespace.

### CODE REVIEW

**Comment by lostintangent** [comment]
@fiveisprime Do we want to make the custom UA string a parameter of the `login` method, and have that automatically propogate to all clients created via the `clientFactory`? That way, you wouldn't have to pass it on each call?

**Comment by fiveisprime** [comment]
Good call. Updated and squashed.

Also updated/squashed https://github.com/lostintangent/azjs/pull/17

**Comment by fiveisprime** [comment]
Ping! I rebased your latest changes onto my fork and it's no longer conflicted. 🤘

**Comment by lostintangent** [comment]
LGTM!

**Pull request merged**
